$(document).ready(function()
{
    $("button").click(function()
    {
        $("#green1").fadeToggle("slow");
        $("#white").fadeToggle("slow");
        $("#green2").fadeToggle("slow");
    });
});
